### ISSUE TITLE
有和finetuned bert的对比吗

### ISSUE THREAD

**Issue by zhihanyang2022** [gitabtion/SoftMaskedBert-PyTorch#19]
作者你好，我看到readme里有softmasked bert的表现，请问有finetuned bert的表现吗？光看softmasked bert的表现看不出有没有效果。谢谢！

**Comment by gitabtion** [comment]
见[https://github.com/gitabtion/BertBasedCorrectionModels](https://github.com/gitabtion/BertBasedCorrectionModels)
