### ISSUE TITLE
CPU无法执行么？

### ISSUE THREAD

**Issue by xyjsjruiliu** [gitabtion/SoftMaskedBert-PyTorch#5]
ruiliu@RuideMacBook-Pro SoftMaskedBert-PyTorch-main % python3.8 main.py --mode main
Namespace(accumulate_grad_batches=16, batch_size=16, bert_checkpoint='bert-base-chinese', device=device(type='cpu'), epochs=10, gpu_index=0, hard_device='cpu', load_checkpoint=False, loss_weight=0.8, lr=0.0001, mode='main', model_save_path='checkpoint', warmup_epochs=8)
GPU available: False, used: False
TPU available: False, using: 0 TPU cores

然后程序就自动退出了，没有响应

**Comment by gitabtion** [comment]
这部分的日志是正常的，没有报错日志么？

________________________________
发件人: Eric ***@***.***>
发送时间: 2021年4月12日 14:55
收件人: gitabtion/SoftMaskedBert-PyTorch ***@***.***>
抄送: Subscribed ***@***.***>
主题: [gitabtion/SoftMaskedBert-PyTorch] CPU无法执行么？ (#5)


ruiliu@RuideMacBook-Pro SoftMaskedBert-PyTorch-main % python3.8 main.py --mode main
Namespace(accumulate_grad_batches=16, batch_size=16, bert_checkpoint='bert-base-chinese', device=device(type='cpu'), epochs=10, gpu_index=0, hard_device='cpu', load_checkpoint=False, loss_weight=0.8, lr=0.0001, mode='main', model_save_path='checkpoint', warmup_epochs=8)
GPU available: False, used: False
TPU available: False, using: 0 TPU cores

然后程序就自动退出了，没有响应

―

**Comment by LuckyyySTA** [comment]
我也遇到了相同的问题，请问您解决了吗？
